name: Create-Release-Draft-Test

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string

jobs:
  call-TagToZip:
    uses: ./.github/workflows/TagToZip.yml
    with:
      tag: ${{ github.event.inputs.tag }}

  call-ReleaseDraft:
    needs: [call-TagToZip]
    uses: ./.github/workflows/CreateReleaseDraftForTag.yml
    with:
      tag: ${{ github.event.inputs.tag }}

