name: Create-Release-Draft-For-Tag

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  Create-Release-Draft-For-Tag:
    runs-on: ubuntu-latest
    steps:
    - name: DownloadArtifact
      uses: actions/download-artifact@v3
      with:
        name: tex-trans-tool-${{ github.event.inputs.tag }}

    - name: Debug
      run: |
        pwd
        ls -alh
        ls -alh ../

    - name: checkout
      uses: actions/checkout@v4
      with:
        path: ./TTTRepo
        fetch-tags: true
        ref: ${{ github.event.inputs.tag }}

    - name: Debug
      run: |
        pwd
        ls -alh
        ls -alh ../


    - name: CrateRelease
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.event.inputs.tag }}
        tag_name: ${{ github.event.inputs.tag }}
        draft: true
        files: |
          tex-trans-tool-${{ github.event.inputs.tag }}.zip
          TTTRepo/package.json