name: tag-to-zip

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  Create-tag-to-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          ref: ${{ github.event.inputs.tag }}
      - name: RemoveDotgit
        run: |
          rm -r ./.git
      - name: Upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: tex-trans-tool-${{ github.event.inputs.tag }}
          path: ./*
