name: tag-to-zip

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  Create-tag-to-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          ref: ${{ github.event.inputs.tag }}

      - name: Debug
        run: |
          pwd
          ls -alh
          ls -alh ../

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: ReinaS-64892/TTT-ImageAssets
          path: .github/ImageAssets

      - name: Debug
        run: |
          pwd
          ls -alh

      - name: ReplaceImageAssets
        run: |
          cp .github/ImageAssets/Image/* ./Image/

      - name: RemoveDotgitAndDotgithub
        run: |
          rm -r ./.git
          rm -r ./.github

      - name: CreateZip
        run: |
          zip -r tex-trans-tool-${{ github.event.inputs.tag }}.zip ./*

      - name: Upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: tex-trans-tool-${{ github.event.inputs.tag }}
          path: tex-trans-tool-${{ github.event.inputs.tag }}.zip
