name: update-version

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  call-Update-Tag:
    uses: ./.github/workflows/UpdatePackageJsonPlasTag.yml
    with:
      tag: ${{ github.event.inputs.tag }}

  call-TagToZip:
    needs: [call-Update-Tag]
    uses: ./.github/workflows/TagToZip.yml
    with:
      tag: ${{ github.event.inputs.tag }}

  call-ReleaseDraft:
    needs: [call-TagToZip]
    uses: ./.github/workflows/CreateReleaseDraftForTag.yml
    with:
      tag: ${{ github.event.inputs.tag }}

